app:
  name: web-app
jobs:
  go_test:
    on:
      pull_request:
      push:
        branches:
          - main
    configs:
      go_test:
        go_version_file: apps/web-app/go.mod
        cache_dependency_path: apps/web-app/go.sum
