app:
  name: hello-world
jobs:
  dev_main:
    on:
      push:
        branches:
          - main
    type: docker_build
    config:
      registry:
        type: aws
        aws:
          iam: dev_main
          repository: dev_main
      tagging: always_latest
      platforms:
        - linux/amd64
  dev_pr:
    on:
      pull_request:
    type: docker_build
    config:
      registry:
        type: aws
        aws:
          iam: dev_main
          repository: dev_main
      tagging: always_latest
      platforms:
        - linux/amd64
