app:
  name: hello-world
jobs:
  dev_main:
    on:
      push:
        branches:
          - main
    configs:
      docker_build:
        registry:
          type: aws
          aws:
            iam: dev_main
            repository: dev_main
        tagging: always_latest
        platforms:
          - linux/amd64
      generic_foo:
        foo: FOO
        bar: BAR
  dev_pr:
    on:
      pull_request:
    configs:
      docker_build:
        registry:
          type: aws
          aws:
            iam: dev_main
            repository: dev_main
        tagging: always_latest
        platforms:
          - linux/amd64
