metadata:
  name: hello-world
jobs:
  dev_main:
    on:
      push:
        branches:
          - main
    loader: docker_build
    docker_build:
      environment:
        type: aws
        aws:
          identity: dev_main
          registry: dev_main
      tagging: always_latest
      platforms: ['linux/amd64']
