app:
  metadata:
    team: backend
    owner: "@yuya-takeyama"
    tier: 1
    slack_channel: "#backend-critical"
    service_type: "api"
    public_facing: true
  depends_on:
    - $root/apps/web-app/pkg
    - $root/apps/web-app/go.mod
    - $root/apps/web-app/go.sum
jobs:
  build_prd:
    metadata:
      priority: critical
      alert_on_failure: true
      estimated_duration: 10
    on:
      push:
        branches:
          - main
    configs:
      docker_build:
        registry:
          type: aws
          aws:
            iam: prd
            repository: prd
        tagging: semver_datetime
        platforms:
          - linux/amd64
      docker_build_go_build:
        go_version_file: apps/web-app/go.mod
        cache_dependency_path: apps/web-app/go.sum
  build_dev_main:
    metadata:
      priority: medium
      alert_on_failure: false
      estimated_duration: 10
    on:
      push:
        branches:
          - main
    configs:
      docker_build:
        registry:
          type: aws
          aws:
            iam: dev_main
            repository: dev_main
        tagging: always_latest
        platforms:
          - linux/amd64
      docker_build_go_build:
        go_version_file: apps/web-app/go.mod
        cache_dependency_path: apps/web-app/go.sum
  build_dev_pr:
    metadata:
      priority: high
      alert_on_failure: false
      estimated_duration: 10
    on:
      pull_request:
    configs:
      docker_build:
        registry:
          type: aws
          aws:
            iam: dev_pr
            repository: dev_pr
        tagging: pull_request
        platforms:
          - linux/amd64
      docker_build_go_build:
        go_version_file: apps/web-app/go.mod
        cache_dependency_path: apps/web-app/go.sum
