name: build-docker

on:
  push:
    branches:
      - main
  pull_request_target:
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**

env:
  CHECKOUT_REF: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      jobs: ${{ env.MONOTONIX_JOBS }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.CHECKOUT_REF }}
          fetch-depth: 0
      - uses: yuya-takeyama/monotonix/actions/load-jobs@4c03ec62c388957c6b5d7ba96694cdc24157aa57 # v0.0.0
        with:
          root-dir: apps
          required-config-keys: 'docker_build'
      - if: ${{ github.event_name == 'pull_request_target' }}
        uses: yuya-takeyama/monotonix/actions/filter-jobs-by-changed-files@4c03ec62c388957c6b5d7ba96694cdc24157aa57 # v0.0.0
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::920373013500:role/monotonix-state-manager
          aws-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/filter-jobs-by-dynamodb-state@4c03ec62c388957c6b5d7ba96694cdc24157aa57 # v0.0.0
        with:
          dynamodb-table: monotonix-state
          dynamodb-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/load-docker-build-job-params@4c03ec62c388957c6b5d7ba96694cdc24157aa57 # v0.0.0
        with:
          global-config-file-path: apps/monotonix-global.yaml
          datetime-tag-timezone: Asia/Tokyo

  build:
    name: ${{ matrix.job.context.label }}
    needs: setup
    if: ${{ needs.setup.outputs.jobs != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    strategy:
      matrix:
        job: ${{ fromJSON(needs.setup.outputs.jobs) }}
    steps:
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::920373013500:role/monotonix-state-manager
          aws-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/set-dynamodb-state-to-running@4c03ec62c388957c6b5d7ba96694cdc24157aa57 # v0.0.0
        with:
          dynamodb-table: monotonix-state
          dynamodb-region: ap-northeast-1
          job: ${{ toJSON(matrix.job) }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ matrix.job.params.docker_build.registry.aws.iam.role }}
          aws-region: ${{ matrix.job.params.docker_build.registry.aws.iam.region }}
      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: ${{ matrix.job.params.docker_build.registry.aws.repository.type }}
      - uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: ${{ matrix.job.params.docker_build.context }}
          push: true
          tags: ${{ matrix.job.params.docker_build.tags }}
          platforms: ${{ matrix.job.params.docker_build.platforms }}
