name: build-docker

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**
  pull_request:
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      build-params: ${{ steps.job-params.outputs.result }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - id: job-configs
        uses: yuya-takeyama/monotonix/actions/load-job-configs@init
        with:
          root-dir: apps
      - run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
          echo "$JOB_CONFIGS"
        env:
          JOB_CONFIGS: ${{ steps.job-configs.outputs.result }}
      - id: job-params
        uses: yuya-takeyama/monotonix/actions/generate-docker-build-job-params@init
        with:
          job-configs: ${{ steps.job-configs.outputs.result }}
          global-config-file-path: apps/monotonix-global.yaml
          datetime-tag-timezone: Asia/Tokyo
      - run: |
          echo "$JOB_PARAMS"
        env:
          JOB_PARAMS: ${{ steps.job-params.outputs.result }}
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::943566097936:role/monotonix-state-read-writer
          aws-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/store-dynamodb-state@init
        with:
          dynamodb-table: monotonix-state
          dynamodb-region: ap-northeast-1
          job-params: ${{ steps.job-params.outputs.result }}
          ttl-hours: 1

  build:
    # name: ${{ matrix.build-params.label }}
    needs: setup
    if: ${{ needs.setup.outputs.build-params != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        job-params: ${{ fromJSON(needs.setup.outputs.build-params) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          echo "$BUILD_PARAMS"
        env:
          BUILD_PARAMS: ${{ toJSON(matrix.job-params) }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ matrix.job-params.param.registry.aws.iam.role }}
          aws-region: ${{ matrix.job-params.param.registry.aws.iam.region }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: ${{ matrix.job-params.param.registry.aws.repository.type }}
      - uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ${{ matrix.job-params.param.context }}
          push: true
          tags: ${{ matrix.job-params.param.tags }}
          platforms: ${{ matrix.job-params.param.platforms }}
