name: build-docker

on:
  push:
    branches:
      - main
  pull_request_target:
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**

env:
  CHECKOUT_REF: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      jobs: ${{ env.MONOTONIX_JOBS }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.CHECKOUT_REF }}
          fetch-depth: 0
      - uses: yuya-takeyama/monotonix/actions/load-jobs@add-claude-to-gitignore
        with:
          root-dir: apps
          required-config-keys: 'docker_build'
      - if: ${{ github.event_name == 'pull_request_target' }}
        uses: yuya-takeyama/monotonix/actions/filter-jobs-by-changed-files@add-claude-to-gitignore
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::920373013500:role/monotonix-state-manager
          aws-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/filter-jobs-by-dynamodb-state@add-claude-to-gitignore
        with:
          dynamodb-table: monotonix-state
          dynamodb-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/load-docker-build-job-params@add-claude-to-gitignore
        with:
          global-config-file-path: apps/monotonix-global.yaml
          timezone: Asia/Tokyo

  build:
    name: ${{ matrix.job.context.label }}
    needs: setup
    if: ${{ needs.setup.outputs.jobs != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.setup.outputs.jobs) }}
    steps:
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::920373013500:role/monotonix-state-manager
          aws-region: ap-northeast-1
      - uses: yuya-takeyama/monotonix/actions/set-dynamodb-state-to-running@add-claude-to-gitignore
        with:
          dynamodb-table: monotonix-state
          dynamodb-region: ap-northeast-1
          job: ${{ toJSON(matrix.job) }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ matrix.job.params.docker_build.registry.aws.iam.role }}
          aws-region: ${{ matrix.job.params.docker_build.registry.aws.iam.region }}
      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: ${{ matrix.job.params.docker_build.registry.aws.repository.type }}
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.job.params.docker_build.context }}
          push: true
          tags: ${{ matrix.job.params.docker_build.tags }}
          platforms: ${{ matrix.job.params.docker_build.platforms }}
