name: build-docker

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**
  pull_request:
    paths:
      - .github/workflows/build-docker.yaml
      - apps/**

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      build-params: ${{ steps.build-params.outputs.jobs }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: build-params
        uses: yuya-takeyama/monotonix/actions/load-job-configs@init
        with:
          root-dir: apps
      - run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
          echo "$JOB_CONFIGS"
        env:
          JOB_CONFIGS: ${{ steps.build-params.outputs.job-configs }}

  build:
    if: ${{ false }}
    name: ${{ matrix.build-params.label }}
    needs: setup
    # if: ${{ needs.setup.outputs.build-params != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        build-params: ${{ fromJSON(needs.setup.outputs.build-params) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          echo "$BUILD_PARAMS"
        env:
          BUILD_PARAMS: ${{ toJSON(matrix.build-params) }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ matrix.build-params.job.config.environment.aws.identity.iam_role }}
          aws-region: ${{ matrix.build-params.job.config.environment.aws.identity.region }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: ${{ matrix.build-params.job.config.environment.aws.registry.type }}
      - uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ${{ matrix.build-params.job.config.context }}
          push: true
          tags: ${{ matrix.build-params.job.config.tags }}
          platforms: ${{ matrix.build-params.job.config.platforms }}
